package com.picus.core.domain.shared.area;

import lombok.Getter;

@Getter
public enum District {

    // 서울특별시
    SEOUL_JONGNO("종로구", Region.SEOUL),
    SEOUL_JUNG("중구", Region.SEOUL),
    SEOUL_YONGSAN("용산구", Region.SEOUL),
    SEOUL_SEONGDONG("성동구", Region.SEOUL),
    SEOUL_GWANGJIN("광진구", Region.SEOUL),
    SEOUL_DONGDAEMUN("동대문구", Region.SEOUL),
    SEOUL_JUNGRANG("중랑구", Region.SEOUL),
    SEOUL_SEONGBUK("성북구", Region.SEOUL),
    SEOUL_GANGBUK("강북구", Region.SEOUL),
    SEOUL_DOBONG("도봉구", Region.SEOUL),
    SEOUL_NOWON("노원구", Region.SEOUL),
    SEOUL_EUNPYEONG("은평구", Region.SEOUL),
    SEOUL_SEODAEMUN("서대문구", Region.SEOUL),
    SEOUL_MAPO("마포구", Region.SEOUL),
    SEOUL_YANGCHEON("양천구", Region.SEOUL),
    SEOUL_GANGSEO("강서구", Region.SEOUL),
    SEOUL_GURO("구로구", Region.SEOUL),
    SEOUL_GEUMCHEON("금천구", Region.SEOUL),
    SEOUL_YOUNGDEUNGPO("영등포구", Region.SEOUL),
    SEOUL_DONGJAK("동작구", Region.SEOUL),
    SEOUL_GWANAK("관악구", Region.SEOUL),
    SEOUL_SEOCHO("서초구", Region.SEOUL),
    SEOUL_GANGNAM("강남구", Region.SEOUL),
    SEOUL_SONGPA("송파구", Region.SEOUL),
    SEOUL_GANGDONG("강동구", Region.SEOUL),

    // 부산광역시
    BUSAN_JUNG("중구", Region.BUSAN),
    BUSAN_SEOGU("서구", Region.BUSAN),
    BUSAN_DONGGU("동구", Region.BUSAN),
    BUSAN_YOUNGDO("영도구", Region.BUSAN),
    BUSAN_JINGU("부산진구", Region.BUSAN),
    BUSAN_DONGNAE("동래구", Region.BUSAN),
    BUSAN_NAMGU("남구", Region.BUSAN),
    BUSAN_BUKGU("북구", Region.BUSAN),
    BUSAN_GANGSEO("강서구", Region.BUSAN),
    BUSAN_HAEUNDAE("해운대구", Region.BUSAN),
    BUSAN_SAHA("사하구", Region.BUSAN),
    BUSAN_GEUMJEONG("금정구", Region.BUSAN),
    BUSAN_YUNJE("연제구", Region.BUSAN),
    BUSAN_SUYEONG("수영구", Region.BUSAN),
    BUSAN_SASANG("사상구", Region.BUSAN),
    BUSAN_GIJANG("기장군", Region.BUSAN),

    // 대구광역시
    DAEGU_JUNG("중구", Region.DAEGU),
    DAEGU_DONG("동구", Region.DAEGU),
    DAEGU_SEOGU("서구", Region.DAEGU),
    DAEGU_NAM("남구", Region.DAEGU),
    DAEGU_BUKGU("북구", Region.DAEGU),
    DAEGU_SUSEONG("수성구", Region.DAEGU),
    DAEGU_DALSEO("달서구", Region.DAEGU),
    DAEGU_DALSEONG("달성군", Region.DAEGU),
    DAEGU_GUNWI("군위군", Region.DAEGU),

    // 인천광역시
    INCHEON_JUNG("중구", Region.INCHEON),
    INCHEON_DONG("동구", Region.INCHEON),
    INCHEON_MICHUHOL("미추홀구", Region.INCHEON),
    INCHEON_YUNSU("연수구", Region.INCHEON),
    INCHEON_NAMDONG("남동구", Region.INCHEON),
    INCHEON_BUPYEONG("부평구", Region.INCHEON),
    INCHEON_GYEYANG("계양구", Region.INCHEON),
    INCHEON_SEOGU("서구", Region.INCHEON),
    INCHEON_GANGHWAGUN("강화군", Region.INCHEON),
    INCHEON_ONGJINGUN("옹진군", Region.INCHEON),

    // 광주광역시
    GWANGJU_DONGGU("동구", Region.GWANGJU),
    GWANGJU_SEOGU("서구", Region.GWANGJU),
    GWANGJU_JUNG("중구", Region.GWANGJU),
    GWANGJU_BUKGU("북구", Region.GWANGJU),
    GWANGJU_GWANGSAN("광산구", Region.GWANGJU),

    // 대전광역시
    DAEJEON_JUNG("중구", Region.DAEJEON),
    DAEJEON_SEOGU("서구", Region.DAEJEON),
    DAEJEON_DONGGU("동구", Region.DAEJEON),
    DAEJEON_YUSEONG("유성구", Region.DAEJEON),
    DAEJEON_DAEDUK("대덕구", Region.DAEJEON),

    // 울산광역시
    ULSAN_JUNG("중구", Region.ULSAN),
    ULSAN_NAM("남구", Region.ULSAN),
    ULSAN_DONG("동구", Region.ULSAN),
    ULSAN_BUKGU("북구", Region.ULSAN),
    ULSAN_ULJU("울주군", Region.ULSAN),

    // 세종특별자치시
    SEJONG_JOCHIWON_EUP("조치원읍", Region.SEJONG),
    SEJONG_YEONGI_MYEON("연기면", Region.SEJONG),
    SEJONG_YEONDONG_MYEON("연동면", Region.SEJONG),
    SEJONG_BUGANG_MYEON("부강면", Region.SEJONG),
    SEJONG_GEUMNAM_MYEON("금남면", Region.SEJONG),
    SEJONG_JANGGUN_MYEON("장군면", Region.SEJONG),
    SEJONG_YEONSEO_MYEON("연서면", Region.SEJONG),
    SEJONG_JUNUI_MYEON("전의면", Region.SEJONG),
    SEJONG_JEONDONG_MYEON("전동면", Region.SEJONG),
    SEJONG_SOJUNG_MYEON("소정면", Region.SEJONG),
    SEJONG_HANSOL_DONG("한솔동", Region.SEJONG),
    SEJONG_SAEROM_DONG("새롬동", Region.SEJONG),
    SEJONG_NASEONG_DONG("나성동", Region.SEJONG),
    SEJONG_DAJEONG_DONG("다정동", Region.SEJONG),
    SEJONG_DODAM_DONG("도담동", Region.SEJONG),
    SEJONG_EOJJIN_DONG("어진동", Region.SEJONG),
    SEJONG_HEAMIL_DONG("해밀동", Region.SEJONG),
    SEJONG_AREUM_DONG("아름동", Region.SEJONG),
    SEJONG_JONGCHON_DONG("종촌동", Region.SEJONG),
    SEJONG_GOUN_DONG("고운동", Region.SEJONG),
    SEJONG_BORAM_DONG("보람동", Region.SEJONG),
    SEJONG_DAEPYUNG_DONG("대평동", Region.SEJONG),
    SEJONG_SODAM_DONG("소담동", Region.SEJONG),
    SEJONG_BANGOK_DONG("반곡동", Region.SEJONG),

    // 경기도
    GYEONGGI_SUWON_JANGAN("수원시 장안구", Region.GYEUNGGI),
    GYEONGGI_SUWON_GWONSEON("수원시 권선구", Region.GYEUNGGI),
    GYEONGGI_SUWON_PALDAL("수원시 팔달구", Region.GYEUNGGI),
    GYEONGGI_SUWON_YOUNGTONG("수원시 영통구", Region.GYEUNGGI),
    GYEONGGI_SEONGNAM_SUJEONG("성남시 수정구", Region.GYEUNGGI),
    GYEONGGI_SEONGNAM_JUNGWON("성남시 중원구", Region.GYEUNGGI),
    GYEONGGI_SEONGNAM_BUNDANG("성남시 분당구", Region.GYEUNGGI),
    GYEONGGI_UIJE("의정부시", Region.GYEUNGGI),
    GYEONGGI_ANYANG_MANAN("안양시 만안구", Region.GYEUNGGI),
    GYEONGGI_ANYANG_DONGAN("안양시 동안구", Region.GYEUNGGI),
    GYEONGGI_BUCHEON_WONMI("부천시 원미구", Region.GYEUNGGI),
    GYEONGGI_BUCHEON_SOSA("부천시 소사구", Region.GYEUNGGI),
    GYEONGGI_BUCHEON_OJEONG("부천시 오정구", Region.GYEUNGGI),
    GYEONGGI_GWANGMYEONG("광명시", Region.GYEUNGGI),
    GYEONGGI_DONGDUCHEON("동두천시", Region.GYEUNGGI),
    GYEONGGI_PYEONGTAEK("평택시", Region.GYEUNGGI),
    GYEONGGI_ANSAN_SANGNOK("안산시 상록구", Region.GYEUNGGI),
    GYEONGGI_ANSAN_DANWON("안산시 단원구", Region.GYEUNGGI),
    GYEONGGI_GOYANG_DEOKYANG("고양시 덕양구", Region.GYEUNGGI),
    GYEONGGI_GOYANG_ILSAN_DONG("고양시 일산동구", Region.GYEUNGGI),
    GYEONGGI_GOYANG_ILSAN_SEO("고양시 일산서구", Region.GYEUNGGI),
    GYEONGGI_GWACHEON("과천시", Region.GYEUNGGI),
    GYEONGGI_GURI("구리시", Region.GYEUNGGI),
    GYEONGGI_NAMYANGJU("남양주시", Region.GYEUNGGI),
    GYEONGGI_OSAN("오산시", Region.GYEUNGGI),
    GYEONGGI_SIHEUNG("시흥시", Region.GYEUNGGI),
    GYEONGGI_GUNPO("군포시", Region.GYEUNGGI),
    GYEONGGI_UIWANG("의왕시", Region.GYEUNGGI),
    GYEONGGI_HANAM("하남시", Region.GYEUNGGI),
    GYEONGGI_YONGIN_CHEOIN("용인시 처인구", Region.GYEUNGGI),
    GYEONGGI_YONGIN_GIHEUNG("용인시 기흥구", Region.GYEUNGGI),
    GYEONGGI_YONGIN_SUJI("용인시 수지구", Region.GYEUNGGI),
    GYEONGGI_PAJU("파주시", Region.GYEUNGGI),
    GYEONGGI_ICHEON("이천시", Region.GYEUNGGI),
    GYEONGGI_ANSUNG("안성시", Region.GYEUNGGI),
    GYEONGGI_GIMPO("김포시", Region.GYEUNGGI),
    GYEONGGI_HWASUNG("화성시", Region.GYEUNGGI),
    GYEONGGI_GWANGJU("광주시", Region.GYEUNGGI),
    GYEONGGI_YANGJU("양주시", Region.GYEUNGGI),
    GYEONGGI_POCHEON("포천시", Region.GYEUNGGI),
    GYEONGGI_YEOJU("여주시", Region.GYEUNGGI),
    GYEONGGI_YEONCHEON("연천군", Region.GYEUNGGI),
    GYEONGGI_GAPYEONG("가평군", Region.GYEUNGGI),
    GYEONGGI_YANGPYEONG("양평군", Region.GYEUNGGI),

    // 충청북도
    CHUNGBOOK_CHEONGJU_SANGDANG("청주시 상당구", Region.CHUNGBUK),
    CHUNGBOOK_CHEONGJU_HEUNGDEOK("청주시 흥덕구", Region.CHUNGBUK),
    CHUNGBOOK_CHEONGJU_SEOWON("청주시 서원구", Region.CHUNGBUK),
    CHUNGBOOK_CHEONGJU_CHEONGWON("청주시 청원구", Region.CHUNGBUK),
    CHUNGBOOK_CHUNGJU("충주시", Region.CHUNGBUK),
    CHUNGBOOK_JECHEON("제천시", Region.CHUNGBUK),
    CHUNGBOOK_BOEUN("보은군", Region.CHUNGBUK),
    CHUNGBOOK_OKCHEON("옥천군", Region.CHUNGBUK),
    CHUNGBOOK_YOUNGDONG("영동군", Region.CHUNGBUK),
    CHUNGBOOK_JUNGPEUNG("증평군", Region.CHUNGBUK),
    CHUNGBOOK_JINCHEON("진천군", Region.CHUNGBUK),
    CHUNGBOOK_GWOESAN("괴산군", Region.CHUNGBUK),
    CHUNGBOOK_EUMSEONG("음성군", Region.CHUNGBUK),
    CHUNGBOOK_DANYANG("단양군", Region.CHUNGBUK),

    // 충청남도
    CHUNGNAM_CHEONAN_DONGNAM("천안시 동남구", Region.CHUNGNAM),
    CHUNGNAM_CHEONAN_SEOBUK("천안시 서북구", Region.CHUNGNAM),
    CHUNGNAM_GONGJU("공주시", Region.CHUNGNAM),
    CHUNGNAM_BORYEONG("보령시", Region.CHUNGNAM),
    CHUNGNAM_ASAN("아산시", Region.CHUNGNAM),
    CHUNGNAM_SEOSAN("서산시", Region.CHUNGNAM),
    CHUNGNAM_NONSAN("논산시", Region.CHUNGNAM),
    CHUNGNAM_GYERYONG("계룡시", Region.CHUNGNAM),
    CHUNGNAM_DANGJIN("당진시", Region.CHUNGNAM),
    CHUNGNAM_GEUMSAN("금산군", Region.CHUNGNAM),
    CHUNGNAM_BUYEO("부여군", Region.CHUNGNAM),
    CHUNGNAM_SEOCHEON("서천군", Region.CHUNGNAM),
    CHUNGNAM_CHEONGYANG("청양군", Region.CHUNGNAM),
    CHUNGNAM_HONGSEONG("홍성군", Region.CHUNGNAM),
    CHUNGNAM_YESA("예산군", Region.CHUNGNAM),
    CHUNGNAM_TAEAN("태안군", Region.CHUNGNAM),

    // 전라남도
    JEONNAM_MOKPO("목포시", Region.JEONNAM),
    JEONNAM_YEOSU("여수시", Region.JEONNAM),
    JEONNAM_SUNCHEON("순천시", Region.JEONNAM),
    JEONNAM_NAJU("나주시", Region.JEONNAM),
    JEONNAM_GWANGYANG("광양시", Region.JEONNAM),
    JEONNAM_DAMYANG("담양군", Region.JEONNAM),
    JEONNAM_GOKSEONG("곡성군", Region.JEONNAM),
    JEONNAM_GURYE("구례군", Region.JEONNAM),
    JEONNAM_GOHEUNG("고흥군", Region.JEONNAM),
    JEONNAM_BOSEONG("보성군", Region.JEONNAM),
    JEONNAM_HWASUN("화순군", Region.JEONNAM),
    JEONNAM_JANGHEUNG("장흥군", Region.JEONNAM),
    JEONNAM_GANGJIN("강진군", Region.JEONNAM),
    JEONNAM_HAENAM("해남군", Region.JEONNAM),
    JEONNAM_YEONGAM("영암군", Region.JEONNAM),
    JEONNAM_MUAN("무안군", Region.JEONNAM),
    JEONNAM_HAMPYEONG("함평군", Region.JEONNAM),
    JEONNAM_YEONGGANG("영광군", Region.JEONNAM),
    JEONNAM_JANGSUNG("장성군", Region.JEONNAM),
    JEONNAM_WANDO("완도군", Region.JEONNAM),
    JEONNAM_JINDO("진도군", Region.JEONNAM),
    JEONNAM_SINAN("신안군", Region.JEONNAM),

    // 경상북도
    GYEONGBUK_POHANG_NAM("포항시 남구", Region.GYEUNGBUK),
    GYEONGBUK_POHANG_BUK("포항시 북구", Region.GYEUNGBUK),
    GYEONGBUK_GYEONGJU("경주시", Region.GYEUNGBUK),
    GYEONGBUK_KIMCHEON("김천시", Region.GYEUNGBUK),
    GYEONGBUK_ANDONG("안동시", Region.GYEUNGBUK),
    GYEONGBUK_GUMI("구미시", Region.GYEUNGBUK),
    GYEONGBUK_YOUNGJU("영주시", Region.GYEUNGBUK),
    GYEONGBUK_YOUNGCHEON("영천시", Region.GYEUNGBUK),
    GYEONGBUK_SANGJU("상주시", Region.GYEUNGBUK),
    GYEONGBUK_MUNGYEONG("문경시", Region.GYEUNGBUK),
    GYEONGBUK_GYEONGSAN("경산시", Region.GYEUNGBUK),
    GYEONGBUK_UISEONG("의성군", Region.GYEUNGBUK),
    GYEONGBUK_CHEONGSONG("청송군", Region.GYEUNGBUK),
    GYEONGBUK_YEONGYANG("영양군", Region.GYEUNGBUK),
    GYEONGBUK_YEONGDEOK("영덕군", Region.GYEUNGBUK),
    GYEONGBUK_CHEONGDO("청도군", Region.GYEUNGBUK),
    GYEONGBUK_GORYEONG("고령군", Region.GYEUNGBUK),
    GYEONGBUK_SEONGJU("성주군", Region.GYEUNGBUK),
    GYEONGBUK_CHILGOK("칠곡군", Region.GYEUNGBUK),
    GYEONGBUK_YECHEON("예천군", Region.GYEUNGBUK),
    GYEONGBUK_BONGHWA("봉화군", Region.GYEUNGBUK),
    GYEONGBUK_ULJIN("울진군", Region.GYEUNGBUK),
    GYEONGBUK_ULLEUNG("울릉군", Region.GYEUNGBUK),

    // 경상남도
    GYEONGNAM_CHANGWON_MASAN_HWOEON("창원시 마산회원구", Region.GYEUNGNAM),
    GYEONGNAM_CHANGWON_MASAN_HAPPO("창원시 마산합포구", Region.GYEUNGNAM),
    GYEONGNAM_CHANGWON_SEONGSAN("창원시 성산구", Region.GYEUNGNAM),
    GYEONGNAM_CHANGWON_UICHANG("창원시 의창구", Region.GYEUNGNAM),
    GYEONGNAM_CHANGWON_JINHAE("창원시 진해구", Region.GYEUNGNAM),
    GYEONGNAM_JINJU("진주시", Region.GYEUNGNAM),
    GYEONGNAM_TONGYEONG("통영시", Region.GYEUNGNAM),
    GYEONGNAM_SACHEON("사천시", Region.GYEUNGNAM),
    GYEONGNAM_KIMHAE("김해시", Region.GYEUNGNAM),
    GYEONGNAM_MILYANG("밀양시", Region.GYEUNGNAM),
    GYEONGNAM_GEOJE("거제시", Region.GYEUNGNAM),
    GYEONGNAM_YANGSAN("양산시", Region.GYEUNGNAM),
    GYEONGNAM_UIRYEONG("의령군", Region.GYEUNGNAM),
    GYEONGNAM_HAMAN("함안군", Region.GYEUNGNAM),
    GYEONGNAM_CHANGNYEONG("창녕군", Region.GYEUNGNAM),
    GYEONGNAM_GOSUNG("고성군", Region.GYEUNGNAM),
    GYEONGNAM_NAMHAE("남해군", Region.GYEUNGNAM),
    GYEONGNAM_HADONG("하동군", Region.GYEUNGNAM),
    GYEONGNAM_SANCHEONG("산청군", Region.GYEUNGNAM),
    GYEONGNAM_HAMYANG("함양군", Region.GYEUNGNAM),
    GYEONGNAM_GEACHANG("거창군", Region.GYEUNGNAM),
    GYEONGNAM_HAPCHEON("합천군", Region.GYEUNGNAM),

    // 전북특별자치도
    JEONBUK_JEONJU_WANSAN("전주시 완산구", Region.JEONBUK),
    JEONBUK_JEONJU_DEOKJIN("전주시 덕진구", Region.JEONBUK),
    JEONBUK_GUNSAN("군산시", Region.JEONBUK),
    JEONBUK_IKSAN("익산시", Region.JEONBUK),
    JEONBUK_JUNGEUP("정읍시", Region.JEONBUK),
    JEONBUK_NAMWON("남원시", Region.JEONBUK),
    JEONBUK_KIMJE("김제시", Region.JEONBUK),
    JEONBUK_JINAN("진안군", Region.JEONBUK),
    JEONBUK_WANJU("완주군", Region.JEONBUK),
    JEONBUK_MUJOO("무주군", Region.JEONBUK),
    JEONBUK_JANGSU("장수군", Region.JEONBUK),
    JEONBUK_IMSIL("임실군", Region.JEONBUK),
    JEONBUK_SUNCHANG("순창군", Region.JEONBUK),
    JEONBUK_GOCHEONG("고창군", Region.JEONBUK),
    JEONBUK_BUAN("부안군", Region.JEONBUK),

    // 제주특별자치도
    JEJU_JEJU("제주시", Region.JEJU),
    JEJU_SEOGWIPO("서귀포시", Region.JEJU);

    private final String displayName;
    private final Region region;

    District(String displayName, Region region) {
        this.displayName = displayName;
        this.region = region;
    }
}
