spring:
  datasource:
    username: ${USERNAME}
    url: ${URL}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  batch:
    job:
      enabled: false
    jdbc:
      isolation-level-for-create: READ_COMMITTED
      initialize-schema: always
      table-prefix: BATCH_

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

