name: PICUS-BE CICD with Docker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      # Gradle 캐시 설정
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Gradle 빌드 (core 디렉토리)
      - name: Build with Gradle Wrapper
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          URL: ${{ secrets.URL }}
        run: |
          cd core
          chmod +x gradlew
          ./gradlew build
      # Docker 이미지 빌드 (Dockerfile은 리포지토리 루트 또는 적절한 위치에 있어야 함)
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/picus:latest .
      # Docker 이미지 푸시 (Docker Hub에 로그인 후 이미지 푸시)
      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/picus:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Deploy to server using Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_PASSWORD }}
          # 원격 서버에서도 Docker Hub 로그인 후 컨테이너를 실행합니다.
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/picus:latest
            docker stop picus || true
            docker rm picus || true
            docker run -d --name picus -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/picus:latest
