name: PICUS-BE CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      # Gradle 캐시 설정
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Gradle 빌드
      - name: Build with Gradle Wrapper
        run: |
          cd core
          ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    # 여기서 secrets에 저장된 값을 직접 env에 할당합니다.
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      URL: ${{ secrets.URL }}
    steps:
      - uses: actions/checkout@v4
      # Gradle 캐시 설정
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Gradle 빌드
      - name: Build with Gradle Wrapper
        run: |
          echo "USERNAME is $USERNAME"
          echo "PASSWORD is $PASSWORD"
          echo "URL is $URL"
          chmod +x gradlew
          ./gradlew build
      # SSH를 통해 원격 서버에 접속하여 애플리케이션 배포
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_PASSWORD }}
          # job 레벨의 env에서 전달한 변수를 원격 스크립트에 전달합니다.
          envs: USERNAME,PASSWORD,URL
          script: |
            # 기존 실행 중인 Java 애플리케이션 종료 (실행 중인 프로세스가 없으면 오류 무시)
            pkill -f 'java -jar' || true
            # 새 애플리케이션 실행 (실제 jar 파일명으로 수정 필요)
            nohup java -jar build/libs/core-0.0.1-SNAPSHOT.jar &
